/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.12
 * Generated at: 2019-07-08 02:45:18 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.view;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class home_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/E:/Emad/grad/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/expert-opinion-test/WEB-INF/lib/spring-webmvc-5.1.3.RELEASE-sources.jar!/META-INF/spring-form.tld", Long.valueOf(1543302572000L));
    _jspx_dependants.put("/WEB-INF/lib/spring-webmvc-5.1.3.RELEASE-sources.jar", Long.valueOf(1560460660924L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"ie=edge\">\n");
      out.write("    \n");
      out.write("    <link rel=\"stylesheet\" href=\"https://use.fontawesome.com/releases/v5.0.13/css/all.css\" integrity=\"sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp\" crossorigin=\"anonymous\">\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css?family=Raleway:100,300,500,700\" rel=\"stylesheet\">\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css?family=Questrial\" rel=\"stylesheet\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/app.css\"/>\n");
      out.write("    <title>Expert Opinion</title>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("    <nav id=\"navbar\" class=\"navbar navbar-expand-md navbar-light\">\n");
      out.write("\n");
      out.write("            <a href=\"welcome\" class=\"navbar-brand\">\n");
      out.write("            \n");
      out.write("            \t<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/exp.png\" width=\"40\" height=\"40\" alt=\"Expert Opinion\">\n");
      out.write("\n");
      out.write("                <h5 class=\"text-light mx-1 d-inline-block\"><strong>Expert Opinion</strong></h5>\n");
      out.write("\n");
      out.write("            </a>\n");
      out.write("\n");
      out.write("            <button class=\"navbar-toggler\" data-toggle=\"collapse\" data-target=\"#mainNavbar\">\n");
      out.write("\n");
      out.write("                <span class=\"navbar-toggler-icon\"></span>\n");
      out.write("\n");
      out.write("            </button>\n");
      out.write("\n");
      out.write("        <div class=\"collapse navbar-collapse\" id=\"mainNavbar\" >\n");
      out.write("\n");
      out.write("            <ul class=\"navbar-nav ml-auto\">\n");
      out.write("\n");
      out.write("                <li  class=\"nav-item\">\n");
      out.write("\n");
      out.write("                    <a href=\"welcome\" class=\"nav-link text-light\"><strong>Home</strong></a>\n");
      out.write("\n");
      out.write("                </li>\n");
      out.write("\n");
      out.write("                <li class=\"nav-item\">\n");
      out.write("\n");
      out.write("                    <a href=\"#about\" class=\"nav-link text-light\"><strong>About Us</strong></a>\n");
      out.write("\n");
      out.write("                </li>\n");
      out.write("\n");
      out.write("                <li class=\"nav-item\">\n");
      out.write("\n");
      out.write("                    <a href=\"#footer\" class=\"nav-link text-light\"><strong>Contact Us</strong></a>\n");
      out.write("\n");
      out.write("                </li>\n");
      out.write("\n");
      out.write("            </ul>\n");
      out.write("\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("    </nav> \n");
      out.write("  \n");
      out.write("\n");
      out.write("    <section id=\"showCase\" class=\"d-flex justify-content-center align-items-center\">\n");
      out.write("\n");
      out.write("        <div id=\"overlay\"></div>\n");
      out.write("\n");
      out.write("        <div class=\"conatiner text-white text-center\" id=\"header\">\n");
      out.write("\n");
      out.write("            <h3 class=\"display-5 mb-0\">A PROFESSIONAL OPINION WITH</h3>\n");
      out.write("\n");
      out.write("            <h1 class=\"display-4\">EXPERT OPINION</h1>\n");
      out.write("\n");
      out.write("            <p class=\"lead d-none d-md-block\"><strong>WE ARE HERE TO MAKE SURE OF YOUR HEALTH</strong> </p>\n");
      out.write("\n");
      out.write("            <div class=\"row justify-content-center\">\n");
      out.write("            \n");
      out.write("\t<div class=\"d-block\">\n");
      out.write("\t\t\t<p>\n");
      out.write("\t\t\t  <button id=\"start\" class=\"btn btn-lg btn-primary px-5 mr-sm-2 m-3\" type=\"button\" data-toggle=\"collapse\" data-target=\"#collapseExample\" aria-expanded=\"false\" aria-controls=\"collapseExample\">\n");
      out.write("\t\t\t    Register Now</button>\n");
      out.write("\t\t\t   \n");
      out.write("\t\t\t   \t<a id=\"start\" href=\"patientLogin\" class=\"btn btn-lg btn-secondary px-5 m-3\">login</a>\n");
      out.write("\t\t\t</p>\n");
      out.write("\t\t\t    \n");
      out.write("\t\t\t    <div class=\"collapse\" id=\"collapseExample\">\n");
      out.write("\t\t\t   \n");
      out.write("\t\t\t    <a href=\"patientFormForAdd\" class=\"btn btn-success d-block d-sm-inline-block mb-2\">As a Patient</a>\n");
      out.write("\t\t\t \t <a href=\"doctorFormForAdd\" class=\"btn btn-warning d-block d-sm-inline-block mb-2\">As a Doctor</a>\n");
      out.write("\t\t\t \t<a href=\"radiologyCenterFormForAdd\" class=\"btn btn-info d-block d-sm-inline-block mb-2\">As a Radiology Center</a>\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t  </div>\n");
      out.write("\t\t\t  \n");
      out.write("\t\t\t </div>\n");
      out.write("   \n");
      out.write("           </div>\n");
      out.write("\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("    </section>\n");
      out.write("\n");
      out.write("    <section id=\"about\">\n");
      out.write("\n");
      out.write("        <div class=\"container text-center mt-4\">\n");
      out.write("\n");
      out.write("            <h2>Join us & Get An Expert opinion</h2>\n");
      out.write("\n");
      out.write("            <div class=\"row\">\n");
      out.write("\n");
      out.write("                <div class=\"col-md-4 p-3\">\n");
      out.write("\n");
      out.write("                    <img src=\"\" alt=\"\" class=\"image-fluid d-none d-md-inline\">\n");
      out.write("\n");
      out.write("                    <h3>Register for free!</h3>\n");
      out.write("\n");
      out.write("                    <p class=\"lead\">Create a free account and get a free instance where you can upload your medical images and retrieve them when you need!</p>\n");
      out.write("\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                <div class=\"col-md-4 p-3\">\n");
      out.write("\n");
      out.write("                        <img src=\"\" alt=\"\" class=\"image-fluid d-none d-md-inline\">\n");
      out.write("\n");
      out.write("                    <h3>Choose the Expert!</h3>\n");
      out.write("\n");
      out.write("                    <p class=\"lead\">Choose the expert that you prefer to send him your medical data and get your report</p>\n");
      out.write("\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                <div class=\"col-md-4 p-3\">\n");
      out.write("\n");
      out.write("                    <img src=\"\" alt=\"\" class=\"image-fluid d-none d-md-inline\">\n");
      out.write("                    \n");
      out.write("                    <h3>It's Totally Safe!</h3>\n");
      out.write("\n");
      out.write("                    <p class=\"lead\">Don't worry we are ensuring your rights in money transfer & also a secure medical info transmission</p>\n");
      out.write("\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("    </section>\n");
      out.write("\n");
      out.write("    <div id=\"bookingModal\" class=\"modal\" tabindex=\"-1\" role=\"dialog\">\n");
      out.write("\n");
      out.write("        <div class=\"modal-dialog\" role=\"document\">\n");
      out.write("\n");
      out.write("            <div class=\"modal-content\">\n");
      out.write("\n");
      out.write("                <div class=\"modal-header\">\n");
      out.write("\n");
      out.write("                    <h5 class=\"modal-title\">Sign Up!</h5>\n");
      out.write("\n");
      out.write("                    <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-label=\"close\">\n");
      out.write("\n");
      out.write("                        <span aria-hidden=\"true\">&times;</span>\n");
      out.write("\n");
      out.write("                    </button>\n");
      out.write("\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                <div class=\"modal-body\">\n");
      out.write("\n");
      out.write("                    <p class=\"lead\">Please fill in all the following fields!</p>\n");
      out.write("\n");
      out.write("                    <form action=\"user.html\">\n");
      out.write("\n");
      out.write("                        <div class=\"form-group\">\n");
      out.write("\n");
      out.write("                            <label for=\"userName\">Username</label>\n");
      out.write("\n");
      out.write("                            <input type=\"text\" class=\"form-control\" id=\"userName\" placeholder=\"Please enter your name\">\n");
      out.write("\n");
      out.write("                        </div>\n");
      out.write("\n");
      out.write("                        <div class=\"form-group\">\n");
      out.write("\n");
      out.write("                            <label for=\"email\">Email</label>\n");
      out.write("\n");
      out.write("                            <input type=\"text\" class=\"form-control\" id=\"email\" placeholder=\"Email@example.com\">\n");
      out.write("\n");
      out.write("                        </div>\n");
      out.write("\n");
      out.write("                        <div class=\"form-group\">\n");
      out.write("\n");
      out.write("                            <label for=\"password\">Choose a Password</label>\n");
      out.write("\n");
      out.write("                            <input type=\"password\" class=\"form-control\" id=\"password\" placeholder=\"Please enter your Password\">\n");
      out.write("\n");
      out.write("                        </div>\n");
      out.write("\n");
      out.write("                        <div class=\"form-group\">\n");
      out.write("\n");
      out.write("                            <label for=\"userType\">Register as</label>\n");
      out.write("\n");
      out.write("                            <select name=\"\" id=\"userType\" class=\"form-control\">\n");
      out.write("\n");
      out.write("                                <option value=\"Patient\">A Patient</option>\n");
      out.write("\n");
      out.write("                                <option value=\"Doctor\">A Doctor</option>\n");
      out.write("\n");
      out.write("                                <option value=\"radiologyCenter\">A Radiology Center</option>\n");
      out.write("\n");
      out.write("                            </select>\n");
      out.write("\n");
      out.write("                        </div>\n");
      out.write("\n");
      out.write("                    </form>\n");
      out.write("\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                <div class=\"modal-footer\">\n");
      out.write("\n");
      out.write("                    <button onclick=\"validate()\" class=\"btn btn-primary\">Submit</button>\n");
      out.write("\n");
      out.write("                    <button class=\"btn btn-secondary\" data-dismiss=\"modal\">Cancel</button>\n");
      out.write("\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("    <div id=\"loginModal\" class=\"modal\" tabindex=\"-1\" role=\"dialog\">\n");
      out.write("\n");
      out.write("            <div class=\"modal-dialog\" role=\"document\">\n");
      out.write("    \n");
      out.write("                <div class=\"modal-content\">\n");
      out.write("    \n");
      out.write("                    <div class=\"modal-header\">\n");
      out.write("    \n");
      out.write("                        <h5 class=\"modal-title\">Login!</h5>\n");
      out.write("    \n");
      out.write("                        <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-label=\"close\">\n");
      out.write("    \n");
      out.write("                            <span aria-hidden=\"true\">&times;</span>\n");
      out.write("    \n");
      out.write("                        </button>\n");
      out.write("    \n");
      out.write("                    </div>\n");
      out.write("    \n");
      out.write("                    <div class=\"modal-body\">\n");
      out.write("    \n");
      out.write("                        <p class=\"lead\">Please fill in all the following fields!</p>\n");
      out.write("    \n");
      out.write("                        <form>\n");
      out.write("    \n");
      out.write("                            <div class=\"form-group\">\n");
      out.write("    \n");
      out.write("                                <label for=\"Email\">Username or Email</label>\n");
      out.write("    \n");
      out.write("                                <input type=\"text\" class=\"form-control\" id=\"Email\" placeholder=\"Username or example@email.com\">\n");
      out.write("    \n");
      out.write("                            </div>\n");
      out.write("    \n");
      out.write("                            <div class=\"form-group\">\n");
      out.write("    \n");
      out.write("                                <label for=\"Password\">Password</label>\n");
      out.write("\n");
      out.write("                                <input type=\"password\" class=\"form-control\" id=\"Password\" placeholder=\"Please enter your Password\">\n");
      out.write("    \n");
      out.write("                            </div>\n");
      out.write("    \n");
      out.write("                        </form>\n");
      out.write("    \n");
      out.write("                    </div>\n");
      out.write("    \n");
      out.write("                    <div class=\"modal-footer\">\n");
      out.write("    \n");
      out.write("                        <button onclick=\"validate2()\" class=\"btn btn-primary\">Login</button>\n");
      out.write("    \n");
      out.write("                        <button class=\"btn btn-secondary\" data-dismiss=\"modal\">Cancel</button>\n");
      out.write("    \n");
      out.write("                    </div>\n");
      out.write("    \n");
      out.write("                </div>\n");
      out.write("    \n");
      out.write("            </div>\n");
      out.write("    \n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("    <section class=\"container-fluid my-3\">\n");
      out.write("\n");
      out.write("        <div class=\"row\">\n");
      out.write("\n");
      out.write("            <div class=\"d-none d-lg-inline col-lg-3\">\n");
      out.write("\n");
      out.write("                <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/mri.jpg\">\n");
      out.write("\n");
      out.write("                <p class=\"lead text-center\">make sure you don't wear any metal wearables</p>\n");
      out.write("\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <div class=\"offset-1 d-none d-lg-inline col-lg-3\">\n");
      out.write("\n");
      out.write("                <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/mammo.jpg\">\n");
      out.write("\n");
      out.write("                <p class=\"lead text-center\">Women above 40 should recheck a mammographic test every 6 months</p>\n");
      out.write("\n");
      out.write("    \n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <div class=\"offset-1 d-none d-lg-inline col-lg-3\">\n");
      out.write("\n");
      out.write("                <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/us.jpg\" class=\"mb-5\">\n");
      out.write("\n");
      out.write("                <p class=\"lead text-center\">Be sure as sometimes to go under US scan, you must not eat or drink up to 6 hours before the test!</p>\n");
      out.write("    \n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("        </div>\n");
      out.write("      \n");
      out.write("\n");
      out.write("    </section>\n");
      out.write("\n");
      out.write("\n");
      out.write("    <section class=\"bg-dark py-3\">\n");
      out.write("\n");
      out.write("        <div class=\"container text-white text-center\">\n");
      out.write("\n");
      out.write("            <p class=\"lead\">Join our mail service to be up to date with new offers!</p>\n");
      out.write("\n");
      out.write("            <div class=\"row justify-content center\">\n");
      out.write("\n");
      out.write("                <div class=\"col-12 col-sm-10 col-md-6 col-lg-4 offset-sm-1 offset-md-3 offset-lg-4\">\n");
      out.write("\n");
      out.write("                    <div class=\"input-group\">\n");
      out.write("\n");
      out.write("                        <input type=\"text\" name=\"\" id=\"\" class=\"form-control\" placeholder=\"youremail@example.com\">\n");
      out.write("\n");
      out.write("                        <div class=\"input-group-append\">\n");
      out.write("\n");
      out.write("                            <button class=\"btn btn-primary\">Join Now!</button>\n");
      out.write("\n");
      out.write("                        </div>\n");
      out.write("\n");
      out.write("                    </div>\n");
      out.write("\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("            </div>\n");
      out.write("            \n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("    </section>\n");
      out.write("\n");
      out.write("    <section id=\"footer\" class=\"bg-secondary d-flex justify-content-center\">\n");
      out.write("\n");
      out.write("        <ul class=\"nav text-center flex-column flex-sm-row\">\n");
      out.write("\n");
      out.write("            <li class=\"nav-item\">\n");
      out.write("\n");
      out.write("                <a href=\"#\" class=\"nav-link text-light\">FAQ</a>\n");
      out.write("\n");
      out.write("            </li>\n");
      out.write("\n");
      out.write("            <li class=\"nav-item \">\n");
      out.write("\n");
      out.write("                    <a href=\"#\" class=\"nav-link text-light\">Contact Us</a>\n");
      out.write("    \n");
      out.write("            </li>\n");
      out.write("\n");
      out.write("            <li class=\"nav-item\">\n");
      out.write("\n");
      out.write("                    <a href=\"#\" class=\"nav-link text-light\" data-toggle=\"modal\" data-target=\"#bookingModal\">Register</a>\n");
      out.write("    \n");
      out.write("            </li>\n");
      out.write("\n");
      out.write("        </ul>\n");
      out.write("        \n");
      out.write("    </section>\n");
      out.write("\n");
      out.write("\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.2.1.slim.min.js\" integrity=\"sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN\" crossorigin=\"anonymous\"></script>\n");
      out.write("<script src=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js\" integrity=\"sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q\" crossorigin=\"anonymous\"></script>\n");
      out.write("<script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js\" integrity=\"sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl\" crossorigin=\"anonymous\"></script>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
